services:
  - type: web
    name: versa-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SUPABASE_STORAGE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: FRONTEND_URL
        sync: false
      - key: API_V1_STR
        value: /api/v1
      - key: PROJECT_NAME
        value: Versatile
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "30"
